services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: taipan-backend-dv
    restart: unless-stopped
    ports:
      - "8083:8082"
      - "6000-6300:5000-5300"
      - "6000-6300:5000-5300/udp"
    volumes:
      - ./data:/opt/taipan/data
      - ./logs:/opt/taipan/logs
      - ./override:/opt/taipan/override
      - ./templates:/opt/taipan/templates
    depends_on:
      - db

  frontend:
    build:
      context: ./taipan-web
      dockerfile: Dockerfile.dev
    container_name: taipan-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_PROXY_TARGET=http://backend:8082
    depends_on:
      - backend

  db:
    image: mariadb:10.11
    container_name: taipan-database-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Bbn2g3X275K
      MYSQL_DATABASE: taipan
      MYSQL_USER: taipan
      MYSQL_PASSWORD: JD96jM5o5K6
    volumes:
      - taipan_db_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d:ro

volumes:
  taipan_db_data:
